name: Test & Upload Report
on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  testng-test-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Run test & generate report
        run: |
          cd testng && mvn test

      - name: Upload report to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: testng-report
          path: reports/

      - name: Upload report to AgileTest.App
        env:
          AGILETEST_BASE_URL: ${{ secrets.AGILETEST_BASE_URL }}
          AGILETEST_CLIENT_TOKEN: ${{ secrets.AGILETEST_CLIENT_TOKEN }}
          PROJECT_KEY: ${{ secrets.PROJECT_KEY }}
          TEST_EXECUTION_KEY: ${{ secrets.TEST_EXECUTION_KEY }}

        run: |
          # Define API endpoint and authorization token
          API_URL="$AGILETEST_BASE_URL/rest/agiletest/1.0/test-executions/automation/testng?projectKey=$PROJECT_KEY&testExecutionKey=$TEST_EXECUTION_KEY&milestoneId=$milestoneId&fixVersions=$fixVersions&revision=$revision&testEnvironments=$testEnvironments&testPlanKeys=$testPlanKeys"

          # Upload report files
          for file in $(find target/surefire-reports -type f -name "*.xml"); do
            echo "Uploading $file to $API_URL"
            curl -X POST "$API_URL" \
              -H "Authorization: Bearer $AGILETEST_CLIENT_TOKEN" \
              -H "Content-Type: application/xml" \
              --data-binary "@$file"
          done
      # After-Run Script
      - name: After-Run Script - Upload Reports
        env:
          AGILETEST_BASE_URL: ${{ secrets.AGILETEST_BASE_URL }}
          AGILETEST_CLIENT_TOKEN: ${{ secrets.AGILETEST_CLIENT_TOKEN }}
          PROJECT_KEY: ${{ secrets.PROJECT_KEY }}
          TEST_EXECUTION_KEY: ${{ secrets.TEST_EXECUTION_KEY }}
        if: always() # Ensures this runs regardless of success/failure of previous steps
        run: |
          echo "Executing after-run script..."
          REPORT_DIR="target/surefire-reports"

          # Check if the report directory exists
          if [ -d "$REPORT_DIR" ]; then
            echo "Found report directory: $REPORT_DIR"
            curl -X POST -H "Content-Type: application/json" -H "Authorization:Bearer $AGILETEST_CLIENT_TOKEN" \
            --data '{ "jobURL":"https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}", "tool":"gitlab", "result":${{ job.status }}}' \
            "$AGILETEST_BASE_URL/rest/agiletest/1.0/test-executions/$TEST_EXECUTION_KEY/pipeline/history?projectKey=$PROJECT_KEY"
          else
            echo "No report directory found. Skipping upload."
          fi
